package net.teunheeftgeenleven.foodextras.item;

import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;
import net.teunheeftgeenleven.foodextras.FoodExtras;

public class ModItemGroups {
    public static final ItemGroup FOOD_ITEMS_GROUP = Registry.register(Registries.ITEM_GROUP, Identifier.of(FoodExtras.MOD_ID, "food_items"),
            FabricItemGroup.builder().icon(()-> new ItemStack(ModItems.PEACH)).displayName(Text.translatable("itemgroup.foodextras.food_items")).
                    entries((displayContext, entries) -> {
                        entries.add(ModItems.CMUF);
                        entries.add(ModItems.MUFFIN);
                        entries.add(ModItems.RICE_BOWL);
                        entries.add(ModItems.STIR_FRY_T1);
                        entries.add(ModItems.STIR_FRY_T2);
                        entries.add(ModItems.STIR_FRY_T3);
                        entries.add(ModItems.STIR_FRY_T4);
                        entries.add(ModItems.STIR_FRY_T5);
                        entries.add(ModItems.KETCHUP);
                        entries.add(ModItems.CHEESE);
                        entries.add(ModItems.PEPERONI);
                        entries.add(ModItems.RPIZ);
                        entries.add(ModItems.PURE);
                        entries.add(ModItems.MILK);
                        entries.add(ModItems.WHITE);
                        entries.add(ModItems.PIZZA);
                        entries.add(ModItems.PSLICE);
                        entries.add(ModItems.TORT);
                        entries.add(ModItems.MINCE);
                        entries.add(ModItems.ONION);
                        entries.add(ModItems.LEEK);
                        entries.add(ModItems.CAPSICUM);
                        entries.add(ModItems.ZUCCHINI);
                        entries.add(ModItems.EGGPLANT);
                        entries.add(ModItems.CORN);
                        entries.add(ModItems.BROCCOLI);
                        entries.add(ModItems.CABBAGE);
                        entries.add(ModItems.SPINACH);
                        entries.add(ModItems.TOMATO);
                        entries.add(ModItems.HOT_PEPPER);
                        entries.add(ModItems.CAULIFLOWER);
                        entries.add(ModItems.MEPI);
                        entries.add(ModItems.MUPI);
                        entries.add(ModItems.TE);
                        entries.add(ModItems.TC);
                        entries.add(ModItems.TBE);
                        entries.add(ModItems.TBC);
                        entries.add(ModItems.TEC);
                        entries.add(ModItems.TBEC);
                        entries.add(ModItems.TB);
                        entries.add(ModItems.TOAST);
                        entries.add(ModItems.PDNUT);
                        entries.add(ModItems.SDNUT);
                        entries.add(ModItems.SUPI);
                        entries.add(ModItems.TACO);
                        entries.add(ModItems.PEACH);
                        entries.add(ModItems.BACON_AND_EGGS);
                        entries.add(ModItems.BANANA);
                        entries.add(ModItems.BANANA_SMOOTIE);
                        entries.add(ModItems.BURGER);
                        entries.add(ModItems.CHERRY);
                        entries.add(ModItems.CHOCOLATE_ICECREAM);
                        entries.add(ModItems.COOKED_BURGER);
                        entries.add(ModItems.COOKED_BACON);
                        entries.add(ModItems.COOKED_EGG);
                        entries.add(ModItems.COOKED_FRIES);
                        entries.add(ModItems.COOKED_PANCAKE);
                        entries.add(ModItems.COOKED_SAUSAGE);
                        entries.add(ModItems.GOLD_KIWI);
                        entries.add(ModItems.HOTDOG);
                        entries.add(ModItems.ICECREAM_AND_SYRUP_PANCAKE);
                        entries.add(ModItems.KETCHUP_HOTDOG);
                        entries.add(ModItems.KIWI);
                        entries.add(ModItems.MUSTARD_HOTDOG);
                        entries.add(ModItems.KETCHUP_AND_MUSTARD_HOTDOG);
                        entries.add(ModItems.ORANGE);
                        entries.add(ModItems.ORANGE_JUICE);
                        entries.add(ModItems.PEAR);
                        entries.add(ModItems.PINEAPPLE);
                        entries.add(ModItems.SPAGHETTI_BOLOGNESE);
                        entries.add(ModItems.SPAGHETTI_BOLOGNESE_WITH_MEATBALLS);
                        entries.add(ModItems.STRACCIATELLA_ICECREAM);
                        entries.add(ModItems.STRAWBERRY_ICECREAM);
                        entries.add(ModItems.STRAWBERRY);
                        entries.add(ModItems.SYRUP_PANCAKE);
                        entries.add(ModItems.VANILLA_ICECREAM);
                        entries.add(ModItems.WAFFLE);
                    }) .build());
    public static final ItemGroup INGEREDENTS_ITEMS_GROUP = Registry.register(Registries.ITEM_GROUP, Identifier.of(FoodExtras.MOD_ID, "ingeredents_items"),
            FabricItemGroup.builder().icon(()-> new ItemStack(ModItems.KNIFE)).displayName(Text.translatable("itemgroup.foodextras.ingeredents_items")).
                    entries((displayContext, entries) -> {

                        entries.add(ModItems.WCRM);
                        entries.add(ModItems.DOUGH);
                        entries.add(ModItems.KETCHUP);
                        entries.add(ModItems.CHEESE);
                        entries.add(ModItems.PEPERONI);
                        entries.add(ModItems.COCA);
                        entries.add(ModItems.KNIFE);
                        entries.add(ModItems.RPIN);
                        entries.add(ModItems.ONION);
                        entries.add(ModItems.LEEK);
                        entries.add(ModItems.CAPSICUM);
                        entries.add(ModItems.ZUCCHINI);
                        entries.add(ModItems.EGGPLANT);
                        entries.add(ModItems.CORN);
                        entries.add(ModItems.BROCCOLI);
                        entries.add(ModItems.CABBAGE);
                        entries.add(ModItems.SPINACH);
                        entries.add(ModItems.TOMATO);
                        entries.add(ModItems.HOT_PEPPER);
                        entries.add(ModItems.CAULIFLOWER);
                        entries.add(ModItems.BSLICE);
                        entries.add(ModItems.RDNUT);
                        entries.add(ModItems.SUROLL);
                        entries.add(ModItems.SALSTICK);
                        entries.add(ModItems.SEASHEETS);
                        entries.add(ModItems.RMUF);
                        entries.add(ModItems.BREAD_BUN);
                        entries.add(ModItems.CRACKED_EGG);
                        entries.add(ModItems.FLOUR);
                        entries.add(ModItems.ICECREAM_CONE);
                        entries.add(ModItems.RMEPI);
                        entries.add(ModItems.RMUPI);
                        entries.add(ModItems.MUSTARD);
                        entries.add(ModItems.RAW_BURGER);
                        entries.add(ModItems.RAW_BACON);
                        entries.add(ModItems.RAW_FRIES);
                        entries.add(ModItems.RAW_PANCAKE);
                        entries.add(ModItems.RAW_SAUSAGE);
                        entries.add(ModItems.CAPSICUM_SEEDS);
                        entries.add(ModItems.BROCCOLIE_SEEDS);
                        entries.add(ModItems.CABBAGE_SEEDS);
                        entries.add(ModItems.CAPSICUM_SEEDS);
                        entries.add(ModItems.CORN_SEEDS);
                        entries.add(ModItems.EGGPLANT_SEEDS);
                        entries.add(ModItems.HOT_PEPPER_SEEDS);
                        entries.add(ModItems.LEEK_SEEDS);
                        entries.add(ModItems.SPINACH_SEEDS);
                        entries.add(ModItems.TOMATO_SEEDS);
                        entries.add(ModItems.ZUCCHINI_SEEDS);
                    }) .build());

    public static void registerItemGroups() {
        FoodExtras.LOGGER.info("Registering Item Groups For "+ FoodExtras.MOD_ID);
    }
}
